package scraper

import (
	"context"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/embedtools/youtube-scraper/internal"
	"github.com/embedtools/youtube-scraper/types"
)

type xmlTranscript struct {
	XMLName xml.Name  `xml:"transcript"`
	Texts   []xmlText `xml:"text"`
}

type xmlText struct {
	Start    string `xml:"start,attr"`
	Duration string `xml:"dur,attr"`
	Text     string `xml:",chardata"`
}

// GetTranscript fetches the transcript/captions for a YouTube video.
func (c *Client) GetTranscript(ctx context.Context, in *types.GetTranscriptInput) (*types.GetTranscriptOutput, error) {
	if ctx.Err() != nil {
		return nil, ErrContextCanceled
	}

	videoID := internal.ExtractVideoID(in.URL)
	if videoID == "" {
		return nil, fmt.Errorf("%w: could not extract video ID from %q", ErrInvalidURL, in.URL)
	}

	playerData, err := c.yt.Player(ctx, videoID)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUpstreamChanged, err)
	}

	captionTracks := extractCaptionTracks(playerData)
	if len(captionTracks) == 0 {
		return nil, fmt.Errorf("%w: no captions available for %s", ErrNotFound, videoID)
	}

	preferredLang := "en"
	if in.Language != "" {
		preferredLang = in.Language
	}

	selectedTrack, autoGenerated := selectCaptionTrack(captionTracks, preferredLang)
	if selectedTrack == nil {
		return nil, fmt.Errorf("%w: no suitable caption track found for %s", ErrNotFound, videoID)
	}

	baseURL := internal.GetString(selectedTrack, "baseUrl")
	if baseURL == "" {
		return nil, fmt.Errorf("%w: caption URL not found", ErrUpstreamChanged)
	}

	// Fetch transcript in JSON3 format, fall back to XML
	segments, err := c.fetchJSON3Transcript(ctx, baseURL+"&fmt=json3")
	if err != nil {
		segments, err = c.fetchXMLTranscript(ctx, baseURL)
		if err != nil {
			return nil, fmt.Errorf("%w: %v", ErrUpstreamChanged, err)
		}
	}

	// Build available languages
	var availableLanguages []types.LanguageInfo
	for _, track := range captionTracks {
		tm, ok := track.(map[string]interface{})
		if !ok {
			continue
		}
		availableLanguages = append(availableLanguages, types.LanguageInfo{
			LanguageCode:   internal.GetString(tm, "languageCode"),
			Name:           internal.GetTextFromRuns(tm, "name"),
			VssID:          internal.GetString(tm, "vssId"),
			IsTranslatable: internal.GetBool(tm, "isTranslatable"),
		})
	}

	// Build full text
	var fullText strings.Builder
	for _, seg := range segments {
		fullText.WriteString(seg.Text)
		fullText.WriteString(" ")
	}

	return &types.GetTranscriptOutput{
		VideoID:            videoID,
		Language:           internal.GetString(selectedTrack, "languageCode"),
		LanguageName:       internal.GetTextFromRuns(selectedTrack, "name"),
		IsAutoGenerated:    autoGenerated,
		Transcript:         segments,
		SegmentCount:       len(segments),
		AvailableLanguages: availableLanguages,
		FullText:           strings.TrimSpace(fullText.String()),
	}, nil
}

func extractCaptionTracks(playerData map[string]interface{}) []interface{} {
	captions, ok := playerData["captions"].(map[string]interface{})
	if !ok {
		return nil
	}
	pc, ok := captions["playerCaptionsTracklistRenderer"].(map[string]interface{})
	if !ok {
		return nil
	}
	ct, ok := pc["captionTracks"].([]interface{})
	if !ok {
		return nil
	}
	return ct
}

func selectCaptionTrack(tracks []interface{}, preferredLang string) (map[string]interface{}, bool) {
	// Exact match
	for _, track := range tracks {
		tm, ok := track.(map[string]interface{})
		if !ok {
			continue
		}
		if internal.GetString(tm, "languageCode") == preferredLang {
			return tm, strings.Contains(internal.GetString(tm, "vssId"), ".a")
		}
	}
	// Prefix match
	for _, track := range tracks {
		tm, ok := track.(map[string]interface{})
		if !ok {
			continue
		}
		if strings.HasPrefix(internal.GetString(tm, "languageCode"), preferredLang) {
			return tm, strings.Contains(internal.GetString(tm, "vssId"), ".a")
		}
	}
	// First available
	if len(tracks) > 0 {
		if tm, ok := tracks[0].(map[string]interface{}); ok {
			return tm, strings.Contains(internal.GetString(tm, "vssId"), ".a")
		}
	}
	return nil, false
}

func (c *Client) fetchJSON3Transcript(ctx context.Context, url string) ([]types.TranscriptSegment, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("transcript request failed with status %d", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	var jsonData map[string]interface{}
	if err := json.Unmarshal(body, &jsonData); err != nil {
		return nil, err
	}

	var segments []types.TranscriptSegment
	events, ok := jsonData["events"].([]interface{})
	if !ok {
		return segments, nil
	}

	for _, event := range events {
		em, ok := event.(map[string]interface{})
		if !ok {
			continue
		}
		if _, hasSegs := em["segs"]; !hasSegs {
			continue
		}

		startMs := internal.GetFloat(em, "tStartMs")
		durationMs := internal.GetFloat(em, "dDurationMs")

		var text strings.Builder
		if segs, ok := em["segs"].([]interface{}); ok {
			for _, seg := range segs {
				if sm, ok := seg.(map[string]interface{}); ok {
					if utf8, ok := sm["utf8"].(string); ok {
						text.WriteString(utf8)
					}
				}
			}
		}

		segText := strings.TrimSpace(text.String())
		if segText != "" {
			segments = append(segments, types.TranscriptSegment{
				Text:     segText,
				Start:    startMs / 1000.0,
				Duration: durationMs / 1000.0,
			})
		}
	}

	return segments, nil
}

func (c *Client) fetchXMLTranscript(ctx context.Context, url string) ([]types.TranscriptSegment, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("transcript request failed with status %d", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	var xmlT xmlTranscript
	if err := xml.Unmarshal(body, &xmlT); err != nil {
		return nil, err
	}

	var segments []types.TranscriptSegment
	for _, t := range xmlT.Texts {
		var start, duration float64
		fmt.Sscanf(t.Start, "%f", &start)
		fmt.Sscanf(t.Duration, "%f", &duration)

		segments = append(segments, types.TranscriptSegment{
			Text:     strings.TrimSpace(internal.DecodeHTMLEntities(t.Text)),
			Start:    start,
			Duration: duration,
		})
	}

	return segments, nil
}
